In [228]:
import os
from pathlib import Path

import kagglehub
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Download the dataset
path = kagglehub.dataset_download(
    "harshadapatil31/student-performance-and-study-habits-dataset"
)
print("Dataset folder:", path)

# Find CSV files in the downloaded folder
csv_files = list(Path(path).rglob("*.csv"))
if not csv_files:
    raise FileNotFoundError(f"No CSV files found in: {path}")

print("CSV files found:", [file.name for file in csv_files])

# Load the first CSV file
csv_path = csv_files[0]
df = pd.read_csv(csv_path)

print("Loaded:", csv_path.name)
print("Working directory:", os.getcwd())
print("Dataset shape:", df.shape)

display(df.head())
df.info()

Dataset folder: C:\Users\prajval gupta\.cache\kagglehub\datasets\harshadapatil31\student-performance-and-study-habits-dataset\versions\1
CSV files found: ['student_performance_dataset.csv']
Loaded: student_performance_dataset.csv
Working directory: c:\Users\prajval gupta\Desktop\Machine learning\Machine Learning\ML_Practice
Dataset shape: (1000, 12)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   object
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          898 non-null    object
 6   internet_access             1000 non-null   object
 7   extracurricular_activities  1000 non-null   object
 8   part_time_job               1000 non-null   object
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [229]:
%pip install kagglehub pandas

Requirement already satisfied: kagglehub in c:\users\prajval gupta\anaconda3\lib\site-packages (1.0.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in c:\users\prajval gupta\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\users\prajval gupta\anaconda3\lib\site-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in c:\users\prajval gupta\anaconda3\lib\site-packages (from kagglehub) (24.1)
Requirement already satisfied: pyyaml in c:\users\prajval gupta\anaconda3\lib\site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in c:\users\prajval gupta\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\prajval gupta\anaconda3\lib\site-packages (from kagglehub) (4.66.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\prajval gupta\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prajval gupta\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prajval gupta\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prajval gupta\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: protobuf in c:\users\prajval gupta\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (4.25.3)
Requirement already satisfied: six>=1.5 in c:\users\prajval gupta\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\prajval gupta\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\prajval gupta\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\prajval gupta\anaconda3\lib\site-packages (from requests->kagglehub) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\prajval gupta\anaconda3\lib\site-packages (from requests->kagglehub) (2026.1.4)
Requirement already satisfied: colorama in c:\users\prajval gupta\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

In [230]:
df.describe()

,student_id,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,3.570700,85.092300,6.799500,69.740900,83.543500
std,288.819436,1.478559,9.270685,1.203527,12.613425,10.341333
min,1.000000,0.500000,54.800000,3.200000,31.300000,46.800000
25%,250.750000,2.600000,78.800000,5.900000,61.000000,76.075000
50%,500.500000,3.600000,85.200000,6.800000,69.600000,83.800000
75%,750.250000,4.500000,91.900000,7.600000,78.400000,91.525000
max,1000.000000,8.100000,100.000000,10.000000,100.000000,100.000000

In [231]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   object
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          898 non-null    object
 6   internet_access             1000 non-null   object
 7   extracurricular_activities  1000 non-null   object
 8   part_time_job               1000 non-null   object
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [232]:
df.columns

Index(['student_id', 'gender', 'study_time_hours', 'attendance_percent',
       'sleep_hours', 'parental_education', 'internet_access',
       'extracurricular_activities', 'part_time_job', 'previous_grade',
       'final_exam_score', 'final_grade'],
      dtype='object')

In [233]:
df['gender'].unique()
map_gender={'Male':1,'Female':2}

In [234]:
df['gender']=df['gender'].map(map_gender)

In [235]:
df['parental_education'].unique()
map_parental_education={'Bachelors':2, 'High School':1, 'Masters':3, 'PhD':4}
df['parental_education']=df['parental_education'].map(map_parental_education)
#df['parental_education']=df['parental_education'].map(map_parental_education).fillna(-5)
df=df.dropna(axis=0)

In [236]:
df['internet_access'].unique()
map_internet_access={'Yes':2,'No':1}
df['internet_access']=df['internet_access'].map(map_internet_access)

In [237]:
df['part_time_job'].unique()
map_part_time_job={'Yes':2,'No':1}
df['part_time_job']=df['part_time_job'].map(map_part_time_job)

In [238]:
df['final_grade'].unique()
map_final_grade={'A':5,'B':4,'C':3,'D':2,'F':1}
df['final_grade']=df['final_grade'].map(map_final_grade)

In [239]:
df['extracurricular_activities'].unique()
df['extracurricular_activities']=df['extracurricular_activities'].map({'Yes':2,'No':1})

In [240]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 898 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  898 non-null    int64
 1   gender                      898 non-null    int64
 2   study_time_hours            898 non-null    float64
 3   attendance_percent          898 non-null    float64
 4   sleep_hours                 898 non-null    float64
 5   parental_education          898 non-null    float64
 6   internet_access             898 non-null    int64
 7   extracurricular_activities  898 non-null    int64
 8   part_time_job               898 non-null    int64
 9   previous_grade              898 non-null    float64
 10  final_exam_score            898 non-null    float64
 11  final_grade                 898 non-null    int64
dtypes: float64(6), int64(6)
memory usage: 91.2 KB

In [241]:
df.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,1,4.0,98.0,6.5,2.0,2,2,1,76.9,100.0,5
1,2,2,6.3,100.0,5.7,1.0,2,2,2,75.5,100.0,5
2,3,1,4.9,85.3,7.9,2.0,2,1,2,88.5,97.3,5
4,5,1,2.2,89.6,4.6,2.0,2,1,2,61.8,68.3,2
5,6,2,4.2,78.2,5.7,1.0,2,1,1,79.8,81.6,4

In [242]:
df.columns

Index(['student_id', 'gender', 'study_time_hours', 'attendance_percent',
       'sleep_hours', 'parental_education', 'internet_access',
       'extracurricular_activities', 'part_time_job', 'previous_grade',
       'final_exam_score', 'final_grade'],
      dtype='object')

In [243]:
feature_names=['gender', 'study_time_hours', 'attendance_percent',
       'sleep_hours', 'parental_education', 'internet_access',
       'extracurricular_activities', 'part_time_job', 'previous_grade',
       'final_exam_score',]

In [244]:
X=df[feature_names]

In [245]:
y=df['final_grade']

In [246]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [247]:
best_k=0
best_score=0
for k in range(1,40):
    KNN=KNeighborsClassifier(n_neighbors=k,p=1)
KNN.fit(X_train_scaled,y_train)

KNeighborsClassifier(n_neighbors=39, p=1)

In [248]:
accuracy=KNN.score(X_test_scaled,y_test)
if accuracy > best_score:
        best_score = accuracy
        best_k = k

print("-" * 30)
print(f"Peak Performance: K = {best_k} achieved {best_score:.4f} accuracy")

------------------------------
Peak Performance: K = 39 achieved 0.7867 accuracy